### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Tomorin114514** [Lorias-Jak/LoriTime#203]
%loritime_afk% The value returned is 'true' or 'false'
I think it was changed to 'afk' or ' '（nothing）is better,because this value is meaningless in TAB
Or change to an editable value

**Comment by Lorias-Jak** [comment]
you have the possibility to change vaules of placeholders within tab. You can stick to that for now.

I will consider adding another placeholder or doing an editable value via the language file


```yml
placeholder-output-replacements:
  '%loritime_afk%':
    'true': ' &4*&4&lAFK&4*&r'
    'false': ''
```

![Image](https://github.com/user-attachments/assets/4b1462b8-114e-426d-9926-97b87c59fdbe)
